### ISSUE TITLE
Configuration won't get deleted when its namespace is being deleted.

### ISSUE THREAD

**Issue by zzxwill** [kubevela/terraform-controller#329]
A Configuration won't get deleted when its namespace is being deleted. Please look into the details of this issue, please refer to https://cloud-native.slack.com/archives/C01BLQ3HTJA/p1656829163511879.

Here are the steps to reproduce the issue.

- Apply the Configuration 

```yaml
apiVersion: terraform.core.oam.dev/v1beta2
kind: Configuration
metadata:
  name: random-e2e
  namespace: n1
spec:
  hcl: |
    resource "random_id" "server" {
      byte_length = 8
    }
    
    output "random_id" {
      value = random_id.server.hex
    }

  inlineCredentials: true

  writeConnectionSecretToRef:
    name: random-conn
    namespace: default
```

- When the Configuration becomes ready, delete namespace `n1`.

The deletion of the Configuration got stuck and there are issues in the log of Terraform Controller.

```shell
apiVersion: terraform.core.oam.dev/v1beta2
kind: Configuration
metadata:
  name: random-e2e
  namespace: n1
spec:
  hcl: |
    resource "random_id" "server" {
      byte_length = 8
    }
    
    output "random_id" {
      value = random_id.server.hex
    }

  inlineCredentials: true

  writeConnectionSecretToRef:
    name: random-conn
    namespace: default
```
