### ISSUE TITLE
[Feature request] Skip destroy if no resource is actually created

### ISSUE THREAD

**Issue by chivalryq** [kubevela/terraform-controller#346]
Hey, I know this is merged, but I realized when you have something wrong the deletion don't complete. For example, Imagine you go to the Cloud provider portal and delete the resource, terraform will fail to delete saying the resource doesn't exist, like this:
```
Error: Error: Subnet: (Name "subnet-1" / Virtual Network Name "vnet-1" / Resource Group "example1") was not found
```

The same happen if I accidentally make a mistake in a HCL and apply some components in an application, but try to delete after realize I did a mistake, the delete never happen.

I just did it on my test environment and can't delete the application even using `force`.

![image](https://user-images.githubusercontent.com/13340485/171449137-1302c7f4-a3b7-43ac-9a3b-c57463145478.png)

I receive a:
```
Deleting Application "vm-1"
force deleted the resources created by application
successfully cleanup the resources created by application, but fail to delete the application
Error: timed out waiting for the condition
```

_Originally posted by @alisson276 in https://github.com/kubevela/kubevela/issues/3929#issuecomment-1143801240_

**Comment by chivalryq** [comment]
Try two wrong applications below. `vela delete -f` works fine. No destroy Job will be created.

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wrong-rds-db
spec:
  components:
    - name: wrong-rds-db
      type: alibaba-rds-database
      properties:
        region: cn-hangzhou
        existing_instance_id: FAKE_ID
        database_name: first_database
        password: U34rfwefwefffaked
        account_name: first_db_account
```

Also see https://github.com/kubevela/terraform-controller/blob/master/controllers/configuration_controller.go#L365-L376 

When `forceDelete` is set. No destroy Job will be created.
